// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4sLQZRUYRVIeZUspILqgnDLB3H7jNLSw',
    appId: '1:409733437252:web:95add7ff263b0860af2911',
    messagingSenderId: '409733437252',
    projectId: 'magic-task-ae057',
    authDomain: 'magic-task-ae057.firebaseapp.com',
    storageBucket: 'magic-task-ae057.appspot.com',
    measurementId: 'G-DKGMRTK942',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSEcXlyILcYh__XSWuuFs36-t1MGhzLgQ',
    appId: '1:409733437252:android:7d08796b23616ea9af2911',
    messagingSenderId: '409733437252',
    projectId: 'magic-task-ae057',
    storageBucket: 'magic-task-ae057.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4qppMGrk5XfgKRKHYN6pGbYtopi5inuE',
    appId: '1:409733437252:ios:e14dc89edc148108af2911',
    messagingSenderId: '409733437252',
    projectId: 'magic-task-ae057',
    storageBucket: 'magic-task-ae057.appspot.com',
    iosClientId: '409733437252-she7qpdiv0puq5a9fumrts0l67psp8rc.apps.googleusercontent.com',
    iosBundleId: 'com.programmer98.magicTask',
  );
}
